# Generated by Django 5.2.1 on 2025-05-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_added_date_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carthistory',
            name='total_price',
        ),
    ]
