# Generated by Django 5.2.1 on 2025-05-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_carthistory_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='shopkeeper_name',
            field=models.CharField(default='temporary', max_length=100),
            preserve_default=False,
        ),
    ]
