# Generated by Django 5.2.1 on 2025-05-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_token_user_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
