# Generated by Django 5.2.1 on 2025-05-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_cart_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='dc_email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
